### ISSUE TITLE
Use more networkx builtins

### ISSUE THREAD

**Issue by danlamanna** [Kitware/romanesco#111]
Right now we [build a large object in memory](https://github.com/Kitware/romanesco/blob/803d3def59203cf06289b5e88ab449c0f3201f6e/romanesco/format/__init__.py#L62), and re-compute it every time a plugin adds a validator/converter.

With ```networkx``` being part of core soon (see #109) - we could potentially refactor/remove [a bit](https://github.com/Kitware/romanesco/blob/803d3def59203cf06289b5e88ab449c0f3201f6e/romanesco/format/__init__.py#L130-L149) of [code](https://github.com/Kitware/romanesco/blob/803d3def59203cf06289b5e88ab449c0f3201f6e/romanesco/utils.py#L211-L246) to use networkx's builtins like [topological sort](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.dag.topological_sort.html) by building up our workflows/validators/converters as DiGraphs and then finding conversion paths using something like [single_source_dijkstra](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.shortest_paths.weighted.single_source_dijkstra.html#networkx.algorithms.shortest_paths.weighted.single_source_dijkstra) (I mention this one because it also has a cut-off in  number of hops away which we currently implement).

This would still involve storing a large object in memory but would only compute paths when they needed to be used, thus allowing plugins to add validators/converters as nodes/edges without any additional computation.

**Comment by zackgalbreath** [comment]
I'll defer to @jeffbaumes on this, but this seems like a good idea to me.  The less roll-your-own code we have to maintain the better.  It would be compelling if we could do a before/after comparison to show that this change results in improved performance and/or reduced memory usage.

**Comment by zachmullen** [comment]
:+1: 

We also have our own toposort implementation that we could get rid of if we want.

**Comment by jeffbaumes** [comment]
@zachmullen I don't think performance/memory will be measurable in the graph sizes we are working with (a few dozen converters so a few dozen links). The biggest potential improvement here is a decrease in our code complexity. Getting rid of a 5-level `for` loop sounds like a win. :+1: 

I like the idea of doing a shortest path search at runtime as long as it's stable (will give the same path each time). I think we could get rid of the arbitrary cutoff of path length 3 and allow arbitrary lengths. I opened #112 as a way for the user to know what happened in the conversion process, including the number of conversions used.

**Comment by zachmullen** [comment]
>  I don't think performance/memory will be measurable in the graph sizes we are working with (a few dozen converters so a few dozen links).

Agreed, memory usage of this structure is not a concern, nor really is time spent traversing it.

> I think we could get rid of the arbitrary cutoff of path length 3 and allow arbitrary lengths.

We may even want to consider some non-negative edge weighting if we want to be able to denote that some conversions are more expensive than others.

**Comment by danlamanna** [comment]
> We may even want to consider some non-negative edge weighting if we want to be able to denote that some conversions are more expensive than others.

I mentioned using weights as a way to avoid paths with lossy intermediary steps. For example the adjacency lists in the graph type aren't going to support node/link metadata for now - so it might make sense to make converting through it more costly.

No reason we couldn't do either or, have multiple weights, and so on.

**Comment by zachmullen** [comment]
Good point, if we start adding properties like "losslessness" to edges we essentially require a logical second graph in which lossy edges are removed (or weighted +∞) for cases when lossless conversion is required.

**Comment by jeffbaumes** [comment]
All super ideas :) lossiness can be a bit tricky to characterize, and people might also be concerned with the type of lossiness, degree of lossiness, etc. Let's keep it simple for now (no weights or edge types) but using networkx certainly opens up these possibilities.
