### ISSUE TITLE
Add temp dir variable to python/R/spark.python tasks

### ISSUE THREAD

**Issue by zachmullen** [Kitware/romanesco#157]
Right now tasks that need to write into the temp directory that they are assigned actually have no direct way of knowing where they should write data. They could infer it by looking at the parent directory of an input file if they have one, but it would be much more valuable to add another special variable called `_tmp_dir` into the custom dict for python, R, and spark execution modes so it could be known directly.

**Comment by jeffbaumes** [comment]
+1 this should be done for the new swift module as well.

**Comment by jeffbaumes** [comment]
Tiny nit: Could we call it `_tempdir` and use `temp` instead of `tmp` for temporary things in romanesco? It seems more pythonic (see https://docs.python.org/2/library/tempfile.html) and would likely be clearer to most people.

**Comment by zachmullen** [comment]
Sure!
