### ISSUE TITLE
bump requests version

### ISSUE THREAD

**Issue by mgrauer** [Kitware/romanesco#194]
Would Romanesco be able to change its requests version to

    requests==2.7.0

or

    requests>=2.6.0

?

I'm running into trouble with incompatible requests versions between girder[requests==2.7.0], romanesco[requests==2.6.0] and minerva[girder-client => requests==2.7.0], while trying to document an install path using as much pip/girder-install as possible.

Current workflow is 

    sudo pip install girder
    git clone romanesco to romanesco_dir
    git clone minerva to minerva_dir
    create worker.local.cfg with spark plugin enabled in romanesco_dir/romanesco
    sudo pip -e .[spark] in romanesco_dir
    sudo girder-install plugin romanesco_dir
    sudo girder-install plugin minerva_dir

**Comment by zachmullen** [comment]
I think romanesco would be fine to move to 2.7.0.
