### ISSUE TITLE
Custom job statuses in girder

### ISSUE THREAD

**Issue by zachmullen** [Kitware/romanesco#199]
We should add a couple of new status codes to the jobs plugin via the romanesco plugin. Namely, `FETCHING_INPUTS` and `PUSHING_OUTPUTS`. Now that we record timestamps on the job for all status changes, this will be very useful information for people to know about jobs: how much time did I spend downloading the data vs. processing it, and on uploading the output?

**Comment by jeffbaumes** [comment]
+1. We could also report `CONVERTING_INPUTS` and `CONVERTING_OUTPUTS` since those might also take up a significant portion of the time.
