### ISSUE TITLE
Girder is not listed as a package requirement

### ISSUE THREAD

**Issue by brianhelba** [Kitware/romanesco#202]
The ``requirements.txt`` file does not list Girder.

**Comment by zachmullen** [comment]
Girder is not a requirement of romanesco.

**Comment by brianhelba** [comment]
@zachmullen So, what's all this: https://github.com/Kitware/romanesco/blob/master/server/__init__.py#L11 ?

**Comment by zachmullen** [comment]
That's the girder plugin part of romanesco. The package itself (the worker) does not depend on girder. Girder plugins don't declare girder as a pip requirement.

On a semi-related note, we are going to move the girder plugin side out of this repo and into girder/girder in the hopefully near future.

**Comment by brianhelba** [comment]
@zachmullen Ah, got it, thanks.
