### ISSUE TITLE
New IO mode: girder

### ISSUE THREAD

**Issue by zachmullen** [Kitware/romanesco#51]
This will use the [girder-client package](https://pypi.python.org/pypi/girder-client/0.1.0) to fetch and push data to girder, and will be aware of girder objects as first-class citizens. For example,

```
{
    "mode": "girder",
    "apiUrl": "http://data.kitware.com/api/v1",
    "token": "...",
    "type": "folder",
    "id": "...",
}
```

**Comment by jeffbaumes** [comment]
Seems like a good idea. +1

**Comment by jeffbaumes** [comment]
I believe #128 fully addresses this. If not please reopen.
