### ISSUE TITLE
Make "inline" the default IO binding mode

### ISSUE THREAD

**Issue by zachmullen** [Kitware/romanesco#87]

**Comment by zachmullen** [comment]
refs #85

**Comment by jeffbaumes** [comment]
@zachmullen is "inline" still not the default?

**Comment by zachmullen** [comment]
The default mode is one called "auto" that attempts to infer the IO made based on the scheme in the "url" field of the input binding. I think some behavior in romanesco depends on this being the case right now, so maybe we should leave that as-is and close this out, if others are OK with how it is now.

**Comment by jeffbaumes** [comment]
Make `"data"` have precedence over `"url"` in `"auto"` mode.
