### ISSUE TITLE
New type and formats: directory/zip, directory/tgz

### ISSUE THREAD

**Issue by zachmullen** [Kitware/romanesco#92]
I've been trying to think of a good way to fit the process of unarchiving an input file into the romanesco architecture, and I think this way makes sense. Example:

```
"task": {
    "inputs": [{
        "id": "a_directory",
        "description": "This is the path to the unarchived directory",
        "type": "string",
        "format": "string"
    }]
}

"inputs": {
    "a_directory": {
        "type": "directory",
        "format": "tgz",   // or "zip"
        "target": "filepath",
        "mode": "http",
        "url": "https://data.kitware.com/file/foo/download" // location of the archive
    }
}
```

Then we can simply rely on the auto-convert process to do the unzipping.

@jeffbaumes does that make sense?

**Comment by jbeezley** [comment]
Is there a reason to use `type = string` in the task spec or is that a typo?

**Comment by zachmullen** [comment]
Well, it would be coming in as a string (the path to the directory), but alternatively I could see:

```
"type": "directory",
"format": "string"
```

in the task input

**Comment by jeffbaumes** [comment]
Types need to match for automatic conversion - at least they way romanesco is currently structured.

So I'd suggest

```
"type": "directory",
"format": "tgz"
```

and

```
"type": "directory",
"format": "path"
```

As the two formats.

**Comment by zachmullen** [comment]
That makes sense.
